alias gco='git checkout'
alias gst='git status'
alias ga='git add'
alias gd='git diff'
alias gdca='git diff --cached'
alias ggpush='git push origin "$(git_current_branch)"'
alias mvni='mvn -Dgpg.skip=true -DskipTests=true clean install'
alias gcmsg='git commit -m'
